version: '3.8'

services:
  llm4logs:
    build: ./
    networks:
      - llm4logs
    entrypoint: ["python", "fine_tuning_inference.py"]
    volumes:
      - ./:/llm4logs

  ollama:
    image: ollama/ollama
    networks:
      - llm4logs
    ports:
      - '11434:11434'
    volumes:
      - ./ollama:/root/.ollama
      - ./huggingface:/root/models/
networks:
  llm4logs:

volumes:
  ollama: